### ISSUE TITLE
ehhhhh

### ISSUE THREAD

**Issue by KaspianDev** [undereducated/ClientDetection-v1#1]
man rly? its a force op?

**Comment by undereducated** [comment]
Does it look like a forceop? I know the plugin is a bit large but that will be fixed today.

**Comment by KaspianDev** [comment]
then why was it removed from spigot? when you fix it post it on spigot

**Comment by k1ndled** [comment]
> then why was it removed from spigot? when you fix it post it on spigot

Some dude reported falsely, so it's under review. That's why it got removed, I'm currently in the process of getting it on CurseForge though. Also, the plugin is fixed I just haven't pushed the update. Sorry for the inconviences

**Comment by undereducated** [comment]
> then why was it removed from spigot? when you fix it post it on spigot

The plugin is no longer on Spigot because it was falsely reported by someone, so it's under review now. The size thing, and other bugs are already fixed I just haven't got the chance to push the update. It's also currently in the process of being accepted onto CurseForge. Sorry for the inconveniences.

**Comment by undereducated** [comment]
v1.0.1 is now pushed, with the new fixes and stuff.

https://github.com/undereducated/ClientDetection-v1/tree/1.0.1

**Comment by KaspianDev** [comment]
i will trust you if you post api code without obfuscation

**Comment by undereducated** [comment]
> i will trust you if you post api code without obfuscation

Maybe we can reach some sort of agreement, I obviously don't feel comfortable posting the entire source as it contains API keys and such, for statistics. But I can probably remove some senstive code and send you it somehow?

**Comment by KaspianDev** [comment]
dude your "api" is literally a malware

**Comment by undereducated** [comment]
> dude your "api" is literally a malware

well it's litterally just meant for utilities within my plugin, statistics and fancy log messages ;-;
modify the code to not use the api if you don't like it that much, or make your own plugin and stop arguing.

**Comment by KaspianDev** [comment]
i dont use something i cant see code of

**Comment by k1ndled** [comment]
> i dont use something i cant see code of
@kacperleague9 

then don't use it, simple as that.

**Comment by dev2adventure** [comment]
I agree 100%! I don't know what is in the code oft the "API" but probably i won't use it...

**Comment by KaspianDev** [comment]
> 
> 
> I agree 100%! I don't know what is in the code oft the "API" but probably i won't use it...

the plugin is a backdoor, dont use it, its confirmed
